const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('Iniciando seed de ms-inventario...');

  // ── Categorías (upsert para re-ejecución segura) ─────────────────────────
  const [medicamentos, alimentos, antiparasitarios, vacunas, higiene, suplementos, accesorios, equipamiento] =
    await Promise.all([
      prisma.categoria.upsert({
        where: { id: 1 },
        update: {},
        create: { nombre: 'Medicamentos', descripcion: 'Fármacos, antibióticos y medicamentos veterinarios' },
      }),
      prisma.categoria.upsert({
        where: { id: 2 },
        update: {},
        create: { nombre: 'Alimentos', descripcion: 'Alimento seco, húmedo y snacks para mascotas' },
      }),
      prisma.categoria.upsert({
        where: { id: 3 },
        update: {},
        create: { nombre: 'Antiparasitarios', descripcion: 'Antipulgas, antigarrapatas y desparasitantes' },
      }),
      prisma.categoria.upsert({
        where: { id: 4 },
        update: {},
        create: { nombre: 'Vacunas', descripcion: 'Vacunas y biológicos veterinarios' },
      }),
      prisma.categoria.upsert({
        where: { id: 5 },
        update: {},
        create: { nombre: 'Higiene y Grooming', descripcion: 'Shampoos, cepillos y productos de limpieza' },
      }),
      prisma.categoria.upsert({
        where: { id: 6 },
        update: {},
        create: { nombre: 'Suplementos', descripcion: 'Vitaminas, minerales y suplementos nutricionales' },
      }),
      prisma.categoria.upsert({
        where: { id: 7 },
        update: {},
        create: { nombre: 'Accesorios', descripcion: 'Collares, correas, juguetes, camas y transportadoras' },
      }),
      prisma.categoria.upsert({
        where: { id: 8 },
        update: {},
        create: { nombre: 'Equipamiento Clínico', descripcion: 'Equipos, instrumental y material veterinario' },
      }),
    ]);

  console.log('Categorías listas.');

  // ── Productos ─────────────────────────────────────────────────────────────
  // stock variado: 0 = agotado | 1-5 = crítico | 6-15 = bajo | 16+ = normal
  const productos = [

    // ── MEDICAMENTOS (10) ────────────────────────────────────────────────
    {
      codigoInterno: 'MED-001',
      nombre: 'Amoxicilina 500mg x 20 tab',
      descripcion: 'Antibiótico de amplio espectro para infecciones bacterianas en perros y gatos',
      marca: 'Vetoquinol',
      fabricante: 'Vetoquinol SA',
      precioCompra: 8500,   precioVenta: 15000,
      cantidadActual: 50,   cantidadMinima: 10, cantidadMaxima: 200,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2027-03-15'),
    },
    {
      codigoInterno: 'MED-002',
      nombre: 'Metronidazol 250mg x 30 tab',
      descripcion: 'Antiprotozoario y antibacteriano para giardia y infecciones digestivas',
      marca: 'Bayer',
      fabricante: 'Bayer Animal Health',
      precioCompra: 6000,   precioVenta: 11500,
      cantidadActual: 35,   cantidadMinima: 8,  cantidadMaxima: 150,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2026-11-20'),
    },
    {
      codigoInterno: 'MED-003',
      nombre: 'Ivermectina 1% Inyectable 50ml',
      descripcion: 'Antiparasitario sistémico de amplio espectro inyectable',
      marca: 'Virbac',
      fabricante: 'Virbac Colombia',
      precioCompra: 18000,  precioVenta: 32000,
      cantidadActual: 8,    cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2026-08-10'),
    },
    {
      codigoInterno: 'MED-004',
      nombre: 'Prednisolona 5mg x 20 tab',
      descripcion: 'Corticoide para procesos inflamatorios y alérgicos',
      marca: 'Medi-Vet',
      fabricante: 'Laboratorios Medi-Vet',
      precioCompra: 5000,   precioVenta: 9500,
      cantidadActual: 20,   cantidadMinima: 8,  cantidadMaxima: 100,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2027-01-05'),
    },
    {
      codigoInterno: 'MED-005',
      nombre: 'Tramadol 50mg Gotas 10ml',
      descripcion: 'Analgésico opioide para dolor moderado a severo en caninos',
      marca: 'Holliday-Scott',
      fabricante: 'Holliday-Scott SA',
      precioCompra: 12000,  precioVenta: 22000,
      cantidadActual: 3,    cantidadMinima: 5,  cantidadMaxima: 40,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2026-09-30'),
    },
    {
      codigoInterno: 'MED-006',
      nombre: 'Enrofloxacina 50mg/ml x 50ml',
      descripcion: 'Antibiótico fluoroquinolona para infecciones respiratorias y urinarias',
      marca: 'Bayer',
      fabricante: 'Bayer Animal Health',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 0,    cantidadMinima: 5,  cantidadMaxima: 50,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2026-12-01'),
    },
    {
      codigoInterno: 'MED-007',
      nombre: 'Furosemida 40mg x 20 tab',
      descripcion: 'Diurético para insuficiencia cardíaca y edemas en animales',
      marca: 'Holliday-Scott',
      fabricante: 'Holliday-Scott SA',
      precioCompra: 4500,   precioVenta: 8000,
      cantidadActual: 15,   cantidadMinima: 6,  cantidadMaxima: 80,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2027-05-12'),
    },
    {
      codigoInterno: 'MED-008',
      nombre: 'Cefalexina 500mg x 12 cápsulas',
      descripcion: 'Antibiótico cefalosporínico para infecciones de piel y tejidos blandos',
      marca: 'Zoetis',
      fabricante: 'Zoetis Colombia',
      precioCompra: 9000,   precioVenta: 17500,
      cantidadActual: 42,   cantidadMinima: 10, cantidadMaxima: 120,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2027-02-28'),
    },
    {
      codigoInterno: 'MED-009',
      nombre: 'Ácido Acetilsalicílico Vet 100mg x 30',
      descripcion: 'Antiinflamatorio y analgésico de uso veterinario',
      marca: 'Medi-Vet',
      fabricante: 'Laboratorios Medi-Vet',
      precioCompra: 3500,   precioVenta: 6500,
      cantidadActual: 1,    cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2026-07-20'),
    },
    {
      codigoInterno: 'MED-010',
      nombre: 'Omeprazol Vet 20mg x 14 comp',
      descripcion: 'Protector gástrico para perros con gastritis o úlceras',
      marca: 'Virbac',
      fabricante: 'Virbac Colombia',
      precioCompra: 7000,   precioVenta: 13000,
      cantidadActual: 28,   cantidadMinima: 8,  cantidadMaxima: 100,
      categoriaId: medicamentos.id,
      fechaVencimiento: new Date('2027-04-10'),
    },

    // ── ALIMENTOS (12) ───────────────────────────────────────────────────
    {
      codigoInterno: 'ALI-001',
      codigoBarras: '7702011234567',
      nombre: 'Royal Canin Medium Adult 3kg',
      descripcion: 'Alimento balanceado para perros adultos de razas medianas',
      marca: 'Royal Canin',
      fabricante: 'Royal Canin Colombia',
      precioCompra: 45000,  precioVenta: 72000,
      cantidadActual: 30,   cantidadMinima: 5,  cantidadMaxima: 100,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-002',
      codigoBarras: '7509546661567',
      nombre: 'Purina Pro Plan Puppy 1.5kg',
      descripcion: 'Alimento para cachorros con DHA para desarrollo cerebral',
      marca: 'Purina',
      fabricante: 'Nestlé Purina PetCare',
      precioCompra: 38000,  precioVenta: 62000,
      cantidadActual: 25,   cantidadMinima: 6,  cantidadMaxima: 80,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-003',
      nombre: "Hill's Science Diet Feline Adult 2kg",
      descripcion: 'Nutrición precisa y equilibrada para gatos adultos',
      marca: "Hill's",
      fabricante: "Hill's Pet Nutrition",
      precioCompra: 52000,  precioVenta: 85000,
      cantidadActual: 18,   cantidadMinima: 4,  cantidadMaxima: 60,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-004',
      codigoBarras: '7891000300671',
      nombre: 'Whiskas Atún en Salsa x 24 sobres',
      descripcion: 'Alimento húmedo para gatos adultos sabor atún en salsa',
      marca: 'Whiskas',
      fabricante: 'Mars Petcare',
      precioCompra: 28000,  precioVenta: 46000,
      cantidadActual: 120,  cantidadMinima: 12, cantidadMaxima: 300,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-005',
      nombre: 'Pedigree Adulto Razas Pequeñas 4kg',
      descripcion: 'Alimento con calcio y vitaminas para perros pequeños adultos',
      marca: 'Pedigree',
      fabricante: 'Mars Petcare',
      precioCompra: 35000,  precioVenta: 58000,
      cantidadActual: 4,    cantidadMinima: 5,  cantidadMaxima: 80,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-006',
      nombre: 'Royal Canin Sterilised Gatos 2kg',
      descripcion: 'Alimento específico para gatos esterilizados con tendencia a sobrepeso',
      marca: 'Royal Canin',
      fabricante: 'Royal Canin Colombia',
      precioCompra: 48000,  precioVenta: 78000,
      cantidadActual: 0,    cantidadMinima: 4,  cantidadMaxima: 50,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-007',
      nombre: 'Cesar Adulto Pollo 100g x 7',
      descripcion: 'Alimento húmedo en gelatina para perros adultos, pack semanal',
      marca: 'Cesar',
      fabricante: 'Mars Petcare',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 60,   cantidadMinima: 8,  cantidadMaxima: 200,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-008',
      nombre: 'Eukanuba Puppy Razas Grandes 3kg',
      descripcion: 'Fórmula DHA para desarrollo óseo en cachorros de razas grandes',
      marca: 'Eukanuba',
      fabricante: 'IAMs Company',
      precioCompra: 55000,  precioVenta: 89000,
      cantidadActual: 5,    cantidadMinima: 4,  cantidadMaxima: 50,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-009',
      nombre: 'Frolic con Pollo y Zanahoria 1kg',
      descripcion: 'Snack completo para perros adultos, formato semihúmedo',
      marca: 'Frolic',
      fabricante: 'Mars Petcare',
      precioCompra: 12000,  precioVenta: 21000,
      cantidadActual: 200,  cantidadMinima: 15, cantidadMaxima: 400,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-010',
      nombre: 'Brit Premium Gatos Sterilised 2kg',
      descripcion: 'Rico en proteína de pollo, bajo en grasas para gatos castrados',
      marca: 'Brit',
      fabricante: 'Brit Care',
      precioCompra: 40000,  precioVenta: 65000,
      cantidadActual: 11,   cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-011',
      nombre: 'Snacks Dentales Pedigree Dentastix x7',
      descripcion: 'Palitos masticables para higiene dental diaria en perros medianos',
      marca: 'Pedigree',
      fabricante: 'Mars Petcare',
      precioCompra: 9000,   precioVenta: 16500,
      cantidadActual: 90,   cantidadMinima: 10, cantidadMaxima: 250,
      categoriaId: alimentos.id,
    },
    {
      codigoInterno: 'ALI-012',
      nombre: 'Fancy Feast Gourmet Salmón 85g x12',
      descripcion: 'Paté de salmón en lata para gatos adultos exigentes',
      marca: 'Fancy Feast',
      fabricante: 'Nestlé Purina PetCare',
      precioCompra: 32000,  precioVenta: 52000,
      cantidadActual: 75,   cantidadMinima: 10, cantidadMaxima: 200,
      categoriaId: alimentos.id,
    },

    // ── ANTIPARASITARIOS (8) ─────────────────────────────────────────────
    {
      codigoInterno: 'ANT-001',
      nombre: 'Frontline Plus Perros 10-20kg x3',
      descripcion: 'Pipetas antipulgas y antigarrapatas de larga duración para perros',
      marca: 'Frontline',
      fabricante: 'Boehringer Ingelheim',
      precioCompra: 38000,  precioVenta: 65000,
      cantidadActual: 22,   cantidadMinima: 6,  cantidadMaxima: 80,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-002',
      nombre: 'Bravecto Masticable Perros 10-20kg',
      descripcion: 'Comprimido masticable con protección hasta 12 semanas contra pulgas y garrapatas',
      marca: 'Bravecto',
      fabricante: 'MSD Animal Health',
      precioCompra: 75000,  precioVenta: 120000,
      cantidadActual: 14,   cantidadMinima: 4,  cantidadMaxima: 50,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-003',
      nombre: 'NexGard Perros 4-10kg x3 comp',
      descripcion: 'Tableta masticable mensual contra pulgas y garrapatas',
      marca: 'NexGard',
      fabricante: 'Boehringer Ingelheim',
      precioCompra: 55000,  precioVenta: 92000,
      cantidadActual: 7,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-004',
      nombre: 'Advantage Gatos hasta 4kg x4',
      descripcion: 'Pipetas antipulgas de aplicación tópica para gatos pequeños',
      marca: 'Advantage',
      fabricante: 'Bayer Animal Health',
      precioCompra: 42000,  precioVenta: 70000,
      cantidadActual: 0,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-005',
      nombre: 'Drontal Plus Perros hasta 35kg x2',
      descripcion: 'Desparasitante intestinal de amplio espectro (tenias, áscaris, anquilostomas)',
      marca: 'Drontal',
      fabricante: 'Bayer Animal Health',
      precioCompra: 18000,  precioVenta: 32000,
      cantidadActual: 40,   cantidadMinima: 8,  cantidadMaxima: 120,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-006',
      nombre: 'Milbemax Gatos Adultos x2 comp',
      descripcion: 'Antiparasitario interno y externo para gatos mayores de 2kg',
      marca: 'Milbemax',
      fabricante: 'Elanco',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 1,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-007',
      nombre: 'Revolution Perros 10-20kg x3 pip.',
      descripcion: 'Antipulgas y antiparasitario interno de uso tópico, control de sarna',
      marca: 'Revolution',
      fabricante: 'Zoetis',
      precioCompra: 68000,  precioVenta: 110000,
      cantidadActual: 9,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: antiparasitarios.id,
    },
    {
      codigoInterno: 'ANT-008',
      nombre: 'Stronghold Gatos 2.6-7.5kg x3',
      descripcion: 'Pipetas antiparasitarias para pulgas, ácaros y parásitos intestinales en gatos',
      marca: 'Stronghold',
      fabricante: 'Zoetis',
      precioCompra: 58000,  precioVenta: 95000,
      cantidadActual: 17,   cantidadMinima: 4,  cantidadMaxima: 50,
      categoriaId: antiparasitarios.id,
    },

    // ── VACUNAS (6) ──────────────────────────────────────────────────────
    {
      codigoInterno: 'VAC-001',
      nombre: 'Vacuna Antirrábica Canina',
      descripcion: 'Vacuna antirrábica inactivada monovalente para perros',
      marca: 'Nobivac',
      fabricante: 'MSD Animal Health',
      precioCompra: 12000,  precioVenta: 25000,
      cantidadActual: 20,   cantidadMinima: 5,  cantidadMaxima: 100,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-10-15'),
    },
    {
      codigoInterno: 'VAC-002',
      nombre: 'Vacuna Séxtuple Canina (DHPPI+L)',
      descripcion: 'Protege contra Distemper, Hepatitis, Parvovirus, Parainfluenza y Leptospira',
      marca: 'Nobivac',
      fabricante: 'MSD Animal Health',
      precioCompra: 22000,  precioVenta: 42000,
      cantidadActual: 15,   cantidadMinima: 5,  cantidadMaxima: 80,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-09-01'),
    },
    {
      codigoInterno: 'VAC-003',
      nombre: 'Vacuna Triple Felina (HCP)',
      descripcion: 'Vacuna contra Herpesvirus, Calicivirus y Panleucopenia felina',
      marca: 'Felocell',
      fabricante: 'Zoetis',
      precioCompra: 18000,  precioVenta: 35000,
      cantidadActual: 0,    cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-08-20'),
    },
    {
      codigoInterno: 'VAC-004',
      nombre: 'Vacuna Bordetella Intranasal',
      descripcion: 'Vacuna contra tos de las perreras (Bordetella bronchiseptica)',
      marca: 'Bronchi-Shield',
      fabricante: 'Zoetis',
      precioCompra: 28000,  precioVenta: 50000,
      cantidadActual: 12,   cantidadMinima: 4,  cantidadMaxima: 50,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-11-30'),
    },
    {
      codigoInterno: 'VAC-005',
      nombre: 'Vacuna Leucemia Felina (FeLV)',
      descripcion: 'Vacuna contra el virus de la leucemia felina',
      marca: 'Purevax',
      fabricante: 'Boehringer Ingelheim',
      precioCompra: 32000,  precioVenta: 58000,
      cantidadActual: 6,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-12-15'),
    },
    {
      codigoInterno: 'VAC-006',
      nombre: 'Vacuna Parvovirus Canino',
      descripcion: 'Vacuna monovalente de emergencia contra Parvovirus CPV-2',
      marca: 'Neopar',
      fabricante: 'MSD Animal Health',
      precioCompra: 15000,  precioVenta: 28000,
      cantidadActual: 3,    cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: vacunas.id,
      fechaVencimiento: new Date('2026-10-01'),
    },

    // ── HIGIENE Y GROOMING (6) ───────────────────────────────────────────
    {
      codigoInterno: 'HIG-001',
      nombre: 'Shampoo Antipulgas Canino 500ml',
      descripcion: 'Shampoo con permetrina para eliminación inmediata de pulgas y garrapatas',
      marca: 'Virbac',
      fabricante: 'Virbac Colombia',
      precioCompra: 18000,  precioVenta: 32000,
      cantidadActual: 35,   cantidadMinima: 6,  cantidadMaxima: 100,
      categoriaId: higiene.id,
    },
    {
      codigoInterno: 'HIG-002',
      nombre: 'Shampoo Medicado Perros Seborreicos 300ml',
      descripcion: 'Con ácido salicílico y azufre para piel seborreica y dermatitis',
      marca: 'Douxo',
      fabricante: 'Sogeval',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 18,   cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: higiene.id,
    },
    {
      codigoInterno: 'HIG-003',
      nombre: 'Limpiador Ótico Veterinario 125ml',
      descripcion: 'Solución limpiadora y secante para canal auditivo de perros y gatos',
      marca: 'Otoclean',
      fabricante: 'Virbac Colombia',
      precioCompra: 14000,  precioVenta: 25000,
      cantidadActual: 14,   cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: higiene.id,
    },
    {
      codigoInterno: 'HIG-004',
      nombre: 'Pasta Dental Canina Sabor Pollo 70g',
      descripcion: 'Pasta dental enzimática sin flúor para perros, reduce placa y sarro',
      marca: 'Virbac',
      fabricante: 'Virbac Colombia',
      precioCompra: 16000,  precioVenta: 28000,
      cantidadActual: 40,   cantidadMinima: 6,  cantidadMaxima: 100,
      categoriaId: higiene.id,
    },
    {
      codigoInterno: 'HIG-005',
      nombre: 'Toallitas Húmedas para Mascotas x50',
      descripcion: 'Toallitas desodorizantes y limpiadoras para ojos, orejas y patas',
      marca: 'Pet Clean',
      fabricante: 'Pet Clean SAS',
      precioCompra: 8500,   precioVenta: 15000,
      cantidadActual: 80,   cantidadMinima: 10, cantidadMaxima: 250,
      categoriaId: higiene.id,
    },
    {
      codigoInterno: 'HIG-006',
      nombre: 'Cepillo Deslizador Doble Cara',
      descripcion: 'Cepillo con púas de acero inoxidable para desenredar y lustrar el pelaje',
      marca: 'FurPet',
      fabricante: 'FurPet Accessories',
      precioCompra: 12000,  precioVenta: 22000,
      cantidadActual: 25,   cantidadMinima: 5,  cantidadMaxima: 80,
      categoriaId: higiene.id,
    },

    // ── SUPLEMENTOS (5) ──────────────────────────────────────────────────
    {
      codigoInterno: 'SUP-001',
      nombre: 'Omega 3 Perros 90 cápsulas',
      descripcion: 'Aceite de salmón EPA/DHA para piel, pelaje y articulaciones',
      marca: 'Vetri-Science',
      fabricante: 'Vetri-Science Laboratories',
      precioCompra: 28000,  precioVenta: 48000,
      cantidadActual: 22,   cantidadMinima: 5,  cantidadMaxima: 80,
      categoriaId: suplementos.id,
    },
    {
      codigoInterno: 'SUP-002',
      nombre: 'Artri-Vet Condroitina + Glucosamina x60',
      descripcion: 'Suplemento articular para perros con displasia o artrosis',
      marca: 'Artri-Vet',
      fabricante: 'Medi-Vet Labs',
      precioCompra: 32000,  precioVenta: 55000,
      cantidadActual: 11,   cantidadMinima: 4,  cantidadMaxima: 60,
      categoriaId: suplementos.id,
    },
    {
      codigoInterno: 'SUP-003',
      nombre: 'Nutri-Cal Pasta Vitamínica 120g',
      descripcion: 'Suplemento energético y vitamínico en pasta para mascotas convalecientes',
      marca: 'Nutri-Cal',
      fabricante: 'Vetoquinol SA',
      precioCompra: 18000,  precioVenta: 32000,
      cantidadActual: 30,   cantidadMinima: 6,  cantidadMaxima: 100,
      categoriaId: suplementos.id,
    },
    {
      codigoInterno: 'SUP-004',
      nombre: 'Calcio Vet Plus 60 comprimidos',
      descripcion: 'Suplemento de calcio, fósforo y vitamina D para perras gestantes y cachorros',
      marca: 'CalciVet',
      fabricante: 'Laboratorios Medi-Vet',
      precioCompra: 10000,  precioVenta: 18500,
      cantidadActual: 2,    cantidadMinima: 5,  cantidadMaxima: 60,
      categoriaId: suplementos.id,
    },
    {
      codigoInterno: 'SUP-005',
      nombre: 'Probióticos FortiFlora Gatos x30 sobres',
      descripcion: 'Probiótico con Enterococcus faecium para equilibrio intestinal felino',
      marca: 'FortiFlora',
      fabricante: 'Nestlé Purina PetCare',
      precioCompra: 55000,  precioVenta: 88000,
      cantidadActual: 3,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: suplementos.id,
    },

    // ── ACCESORIOS (7) ───────────────────────────────────────────────────
    {
      codigoInterno: 'ACC-001',
      nombre: 'Collar Antipulgas Seresto Perros Grandes',
      descripcion: 'Collar de 8 meses de protección continua contra pulgas y garrapatas',
      marca: 'Seresto',
      fabricante: 'Bayer Animal Health',
      precioCompra: 35000,  precioVenta: 58000,
      cantidadActual: 15,   cantidadMinima: 3,  cantidadMaxima: 50,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-002',
      nombre: 'Correa Retráctil 5m Perros Medianos',
      descripcion: 'Correa retráctil con freno manual, hasta 20kg',
      marca: 'Flexi',
      fabricante: 'Flexi-Bogert & Voss',
      precioCompra: 28000,  precioVenta: 48000,
      cantidadActual: 20,   cantidadMinima: 4,  cantidadMaxima: 60,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-003',
      nombre: 'Arnés Acolchado Perros Talla M',
      descripcion: 'Arnés con doble ajuste y tira reflectante para paseos seguros',
      marca: 'Ruffwear',
      fabricante: 'Ruffwear Inc.',
      precioCompra: 38000,  precioVenta: 65000,
      cantidadActual: 8,    cantidadMinima: 4,  cantidadMaxima: 40,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-004',
      nombre: 'Cama Ortopédica Perros Grandes',
      descripcion: 'Cama viscoelástica para perros con displasia o problemas articulares',
      marca: 'MemoryPet',
      fabricante: 'PetComfort SAS',
      precioCompra: 85000,  precioVenta: 145000,
      cantidadActual: 4,    cantidadMinima: 2,  cantidadMaxima: 20,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-005',
      nombre: 'Bebedero Automático Eléctrico 2L',
      descripcion: 'Fuente de agua con filtro de carbón activo y circulación continua',
      marca: 'PetSafe',
      fabricante: 'Radio Systems Corp.',
      precioCompra: 55000,  precioVenta: 92000,
      cantidadActual: 300,  cantidadMinima: 5,  cantidadMaxima: 500,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-006',
      nombre: 'Transportadora Plástica Gatos Mediana',
      descripcion: 'Guacal de polipropileno con ventilación lateral y puerta metálica',
      marca: 'Vari Kennel',
      fabricante: 'Petmate',
      precioCompra: 65000,  precioVenta: 110000,
      cantidadActual: 7,    cantidadMinima: 2,  cantidadMaxima: 20,
      categoriaId: accesorios.id,
    },
    {
      codigoInterno: 'ACC-007',
      nombre: 'Juguete Kong Classic Perros Talla M',
      descripcion: 'Juguete de caucho resistente para rellenar con snacks y estimulación mental',
      marca: 'Kong',
      fabricante: 'Kong Company',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 45,   cantidadMinima: 5,  cantidadMaxima: 100,
      categoriaId: accesorios.id,
    },

    // ── EQUIPAMIENTO CLÍNICO (3) ─────────────────────────────────────────
    {
      codigoInterno: 'EQP-001',
      nombre: 'Jeringas Desechables 5ml x100',
      descripcion: 'Jeringas estériles luer-slip con aguja 22G para uso veterinario',
      marca: 'BD',
      fabricante: 'Becton Dickinson',
      precioCompra: 18000,  precioVenta: 32000,
      cantidadActual: 200,  cantidadMinima: 20, cantidadMaxima: 500,
      categoriaId: equipamiento.id,
    },
    {
      codigoInterno: 'EQP-002',
      nombre: 'Guantes de Nitrilo Talla M x100',
      descripcion: 'Guantes de examen sin polvo, resistentes a químicos para uso clínico',
      marca: 'Kimberly-Clark',
      fabricante: 'Kimberly-Clark Health',
      precioCompra: 22000,  precioVenta: 38000,
      cantidadActual: 150,  cantidadMinima: 15, cantidadMaxima: 400,
      categoriaId: equipamiento.id,
    },
    {
      codigoInterno: 'EQP-003',
      nombre: 'Termómetro Digital Veterinario',
      descripcion: 'Termómetro rectal de punta flexible con resultado en 10 segundos',
      marca: 'Geratherm',
      fabricante: 'Geratherm Medical AG',
      precioCompra: 12000,  precioVenta: 22000,
      cantidadActual: 0,    cantidadMinima: 3,  cantidadMaxima: 20,
      categoriaId: equipamiento.id,
    },
  ];

  // Asociar imagen SVG generada a cada producto
  for (const p of productos) {
    if (!p.imagen) {
      p.imagen = `/api/v1/uploads/productos/${p.codigoInterno}.svg`;
    }
  }

  let creados = 0;
  let omitidos = 0;

  for (const producto of productos) {
    const existe = await prisma.producto.findUnique({
      where: { codigoInterno: producto.codigoInterno },
    });

    if (existe) {
      // Si el producto existe pero aún no tiene imagen, actualizarla
      if (!existe.imagen && producto.imagen) {
        await prisma.producto.update({
          where: { codigoInterno: producto.codigoInterno },
          data: { imagen: producto.imagen },
        });
      }
      omitidos++;
      continue;
    }

    await prisma.producto.create({ data: producto });
    creados++;
  }

  console.log(`Categorías: ${8} upserted`);
  console.log(`Productos creados: ${creados} | Ya existían (omitidos): ${omitidos}`);
  console.log('Seed de ms-inventario completado.');
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (e) => {
    console.error('Error en seed:', e.message);
    await prisma.$disconnect();
    process.exit(1);
  });
